server:
  port: 12345
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "wJjSKhO1D6p3xv+J9Q0Vd7EpjbCnS4uS1Pa8TNoLfDg="
  expiration: 86400000
  refresh:
    expiration: 604800000
