spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenvanvu14022005@gmail.com
    password: nfsc jhjf urlp fatl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        transport:
          protocol: smtp
        debug: true
  application:
    name: common-service
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      host: localhost
      port: 6379
      timeout: 2000


server:
  port: 8088

common:
  kafka:
    bootstrap-servers: localhost:9092
    key: org.apache.kafka.common.serialization.StringSerializer
    value: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    retries: 3
    batch-size: 16384
    buffer-memory: 33554432
    compression-type: gzip

    group-id: my-consumer-group
    auto-offset-reset: earliest
    enable-auto-commit: true


